language: python
python:
  - "2.7"
cache: pip

sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.9.0

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - docker --version

addons:
  apt:
    packages:
      - libblas-dev
      - liblapack-dev
      - libatlas-base-dev

script:
  - make dev.coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
